name: mFreeze
load: POSTWORLD
version: 1.2
api: 4.0.0
main: hausemaster3734\mFreeze\Loader
author: Hausemaster3734
permissions:
  mfreeze.command.use:
    description: A simple permission.
    default: op
